CREATE TABLE IF NOT EXISTS doctors (
  DoctorID INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Phone VARCHAR(15) NOT NULL,
  Specialty VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS patients (
  PatientID INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  DOB DATE,
  Phone VARCHAR(15) NOT NULL,
  Address VARCHAR(200),
  Gender VARCHAR(10),
  InsuranceName VARCHAR(100),
  InsuranceID VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS appointments (
  DoctorID INT NOT NULL,
  PatientID INT NOT NULL, 
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  Status VARCHAR(20) NOT NULL DEFAULT 'Scheduled',
  Description TEXT,
  
  PRIMARY KEY (DoctorID, PatientID, `Date`, `Time`),
  FOREIGN KEY (DoctorID) REFERENCES doctors(DoctorID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (PatientID) REFERENCES patients(PatientID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emergencyContacts (
  PatientID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Relationship VARCHAR(50),
  Phone VARCHAR(15) NOT NULL,
  Email VARCHAR(100),
  
  PRIMARY KEY (PatientID, Name),
  FOREIGN KEY (PatientID) REFERENCES patients(PatientID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
